### ISSUE TITLE
Layout sorting question

### ISSUE THREAD

**Issue by bastuijnman** [fmtvp/tal#222]
Hi Guys,

I've got a small question we have been debating internally in our company here. What was the reason for using the width of the second sort value for *ad* in getBestFitLayout in application.js? And is there a reason for not just using the calculated surface area?

```javascript
_layouts.sort(function(a, b) {
    var ad = (a.width*a.width) + (a.height*b.height), // so the b.height here?
        bd = (b.width*b.width) + (b.height*b.height);
    if(ad == bd) return 0;
    else if(ad < bd) return 1;
    else return -1;
});
```
Thanks in advance!

**Comment by dhurrell** [comment]
Hi bastuijnman,

We can't think of a good reason why we're using b.height in the calculation for _ad_, so it may simply be a mistake that's gone unnoticed due to the standard TV resolutions we use. Is it causing you a problem?

I'm not sure why this algorithm (comparing diagonal sizes) was used in preference to comparing surface area. Similarly, I suppose for the resolutions we're using, it doesn't make any difference.

Sorry I can't be more helpful!

**Comment by bastuijnman** [comment]
Thanks for the answer anyway :+1:
