### ISSUE TITLE
cehtml background overlay

### ISSUE THREAD

**Issue by lukejpreston** [fmtvp/tal#246]
cehtml devices put the video behind the background
The work around we have for all devices is to make the background invisible and application background invisible like so

```
background-image: none !important;
background-color: transparent !important;
```
This could be done at a TAL level for all devices instead of code level as and anyone who wants a background overlaid on the video should be adding it anyway

**Comment by sdclibbery** [comment]
Thanks for the report Luke :-)

To give some more background, the OIPF (CEHTML) spec requires the video content to be fullscreen and behind all HTML content, which is why we wanted to adopt this as a consistent approach for all device types in the 'new' TAL Media Player API. We have provided a consistent abstraction by making sure that the video was _always_ fullscreen and behind all other HTML TAL content, on all devices (not just CEHTML).

However, it became clear that this would cause another problem: when developing and testing TAL apps in a desktop browser (using the HTML5 Media Player strategy), the app would be sized to its correct size (eg 720 or 1080 within the browser window), but the video would be the full size of the browser window. This was very confusing to developers and made it hard to test TAL app layouts correctly.

So in the end we decided to break the consistency of the Media Player API by making the HTML5 Media Player place its video element as a child of the TAL root widget. This keeps the video at the size of the TAL app, but now gives us somewhat inconsistent behaviour whereby the app root widget background must be cleared for the video to be visible, but _only_ on CEHTML devices :-/

Your suggestion for fixing this makes sense: if TAL were to ensure that its root widget and body elements have a cleared, transparent background, then this would restore consistency because all video would be visible in the same way.

**Comment by CPatBBC** [comment]
This has been logged as Jira ticket https://jira.dev.bbc.co.uk/browse/TVPJSFRMWK-2403, which is now in the TAL platform backlog for consideration.

**Comment by tsadlerBBC** [comment]
Closing this issue, as we have raised an internal tickets and do not believe this will be dealt with anytime soon.

We do not feel confident that we can implement a solution to this without a proper piece of analysis. This would include the option of implementing this in a higher level of the platform, rather than TAL.
