### ISSUE TITLE
Not able to select what I want on the Sample App

### ISSUE THREAD

**Issue by Guisch** [fmtvp/tal#248]
Hi guys !

So I just started a TAL project yesterday and to to familiarize myself with TAL, I just decide to launch the sample Application on my Samsung TV.
As I wasn't able to test it directly on my device, I just decide to create a local Web server and connect to the Sample Application via the Web browser of my Samsung.
And that does look bad.. The selector was erratic. Just take a look by yourself
https://mega.co.nz/#!xkt0lJAQ!iFwIQIOiafJcH6DNF9pYfCJLbaouxPZqykA9dVJhF3g
https://mega.co.nz/#!U4kVRa6Y!I_njOdAPQ8xENEMtP-fNf4djfMjWP7lAHXF0zVdkuIk

I use Wamp Server (lastest version: Apache : 2.4.9 MySQL : 5.6.17 PHP : 5.5.12 PHPMyAdmin : 4.1.14 SqlBuddy : 1.3.3 XDebug : 2.2.5): http://www.wampserver.com/
The sample app was this one: https://github.com/fmtvp/talexample

So here's my question: Is there a difference between deploying the app onto the tv vs just the web version ?

Thanks !

**Comment by dhurrell** [comment]
Hi Guisch,

The most likely explanation for the problems you're seeing is that you don't have a Samsung device configuration file containing the correct Samsung keycodes (although the fact that the key presses appear to work _sometimes_ is a little strange). Apologies that we do not supply any Samsung configs.

You can create a Samsung config for yourself by taking default-webkit-default.json from config/devices in TAL as a base and creating, for instance, samsung-x12-default.json. The correct keycodes can be found by clicking the "Handling Remote Control Key Events" link in these search results:
http://www.samsungdforum.com/Search/UnifiedSearchAll?schoption=&schloc=SCH_PAGE&hdnSchText=keycode

(e.g. the code for "ENTER" is 29443).

While you're there, you should also update the "modifiers" section to use the appropriate Samsung parts of TAL where available (e.g. "antie/devices/mediaplayer/samsung_maple" instead of "html5", etc).

Load the new config file into the TAL example app by starting it with the "brand" and "model" query string parameters. For instance, if your config is called samsung-x12-default.json:
http://1.2.3.4/?brand=samsung&model=x12

Running an app in the Samsung browser will give different results to running it deployed on the TV as part of a Samsung widget; in general you will have less access to the device APIs and you may not be able to do things such as control broadcast. However, I think that simple on-screen navigation should be the same, but I'm not certain.

You should be able to find information on developing a Samsung widget in their developer forum:
http://www.samsungdforum.com/

You can follow their instructions to produce a widget containing TAL, your own application code and a simple index page, loaded when you run the widget, to initialise it all.

Hope this is helpful.

**Comment by tsadlerBBC** [comment]
Hi @Guisch, 

Has David's advice solved your issue?

Thanks,

Tom

**Comment by Guisch** [comment]
I'm not able to try it know, sorry.
I keep you in touch.

**Comment by tsadlerBBC** [comment]
Thanks @Guisch,

We'll close this for now, but feel free to re-open this or raise another issue should you need any further help.

Tom
