### ISSUE TITLE
Array.indexOf implementation

### ISSUE THREAD

**Issue by joeyjojo** [fmtvp/tal#273]
I find https://github.com/fmtvp/tal/pull/271 to be a really weird implementation of 'shimming' this function.

Can we look at this again please?

Firstly, I think we should have decided to do the whole of the ES5 shim but that asides!

If we decided that only shimming out this particular function is valuable and what we want to do, then:

1. Having it in a separate require module is odd, what if we need this before bootstrap. IMO we should say we expect this to be there BEFORE we bootstrap.

If we have decided that we don't want to do that then:

2. We should do this ASAP in the bootstrap code
3. We should do this only once.
4. We shouldn't need to import this every time we need it incase we change the ordering of the imports.
5. Adding it as a 'static import' like we have done is error prone because it doesn't because it affects the argument order in the require define.

**Comment by dhurrell** [comment]
I don't think this is intended to be a final answer to the shimming question. It's the minimum required to get #264 working on non-ES5 devices.

Using a require module to set up the shim seems sensible to me - it's the easiest way to include it without messing around with some additional bootstrapping code, which would need to go into all client apps. As a dependency of antie/application (albeit through multiple levels of indirection) it is one of the first modules to be loaded, and it will definitely load before anything outside of TAL.

**Comment by joeyjojo** [comment]
Given what you say is true, I still feel that we should move it to application itself (or whatever module is loaded first) rather than its dependents.

If for whatever reason we were to use it before the 2 things that currently use it, we would have to require it there as well.

I don't think the above answers some of my other reservations with the implementation. 

Requiring in multiple times something that modifies the prototype is unexpected and unnecessary.
Requiring in something that is never 'used' (ie it is not then an argument) leads to buggy error prone code in the future.

So whilst I can agree with most of your statement, I feel this should be require-d in ASAP in the bootstrapping code and done only once.

**Comment by dhurrell** [comment]
Agreed generally - although I'm not sure requiring the shim module into antie/application would guarantee it loads before the modules that currently have it as a dependency. This does need a bit more thought. :+1:

**Comment by sdclibbery** [comment]
There were two problems to be fixed by this work; the first was the failing Biscuit unit tests, the second was that Sport got broken because it used the widget/event stuff too early in the bootstrap process. Do we know if this change has event fixed Sport? It seems like it probably wont have..? In which case a much earlier shimming in is not just desirable, but essential..?

**Comment by dhurrell** [comment]
It has fixed it. Making the shim module a dependency of the modules where it's used guarantees that it will be loaded before it's needed.

**Comment by sdclibbery** [comment]
OK yes that makes sense. I do still agree with Jon that this should be
treated more like a shim instead of something you have to require in.

Also have a look at lines 41 and 43 in here:
https://github.com/fmtvp/tal/blob/0c9857d63cdf9fb626ed4c4eb35b36f2461e39d6/static/script/events/event.js

We now have a mismatch between the things we are requiring in, and the
parameters to the function. This is going to  be a big pain next time we
need to require another module into this one. It also feels like a bad use
of require to require a file for its side effects, not because we need to
get a reference to it (if you see what I mean).

I definitely think we should bring this shim in as a basic part of TAL and
not expect other code to have to require it in.

**Comment by AlexChesters** [comment]
:+1: Came across this is issue again last week, it feels strange that this is something that gets "required" in

**Comment by tsadler1988** [comment]
Current plan is for TAL to expect ES5 to be supported, and either the device's browser to support ES5, or the server to load ES5 shim into the page.

**Comment by AlexChesters** [comment]
@tsadler1988 does that mean our Array.indexOf shim should be considered deprecated? and removed in the next major version of `tal`?

**Comment by tsadler1988** [comment]
Ideally, yes, but I don't think it's wise to deprecate until all of our TAL apps' indexes load the ES5 shim,.

**Comment by AlexChesters** [comment]
Yeah that's fair enough. Hopefully that won't be too long!

**Comment by tsadler1988** [comment]
Update on this:

As of TAL 5.0.0 our policy will be that ES5 is supported. This is indicated by es5-shim being defined in our package.json as a dependency (see https://github.com/fmtvp/tal/commit/7a994aef55891821a438709e72089b982b28ec64) TAL app developers will be responsible for shimming ES5 if they intend to run TAL apps on devices that do not support ES5.

In TAL 6.0.0 we intend to remove Device.arrayIndexOf and lib/array.indexOf.js.

**Comment by subsidel** [comment]
I have opened #394 to hopefully resolve this :)

**Comment by AlexChesters** [comment]
@subsidel can we close this and make @joeyjojo incredibly happy?

**Comment by subsidel** [comment]
yes

**Comment by tsadler1988** [comment]
🎆
