### ISSUE TITLE
CE HTML player does not move to the error state on device error

### ISSUE THREAD

**Issue by LarsGrevelink** [fmtvp/tal#355]
Is there a reason for the decision to make the device error not move to the local error state of the mediaplayer. It currently only reports the error, but let the player be on the buffering state.

The code I'm talking about is the following;
https://github.com/fmtvp/tal/blob/master/static/script/devices/mediaplayer/cehtml.js#L328

We patched it in our code to match functionality of other players throwing errors. I could make a PR if this is in the line of your thinking.

Let me know and thanks in advance,

Lars Grevelink
24i

**Comment by tsadler1988** [comment]
Hi Lars,

This is true for all implementations of the TAL Media Player (CEHTML, HTML5, Samsung Maple). Devices will often raise non-fatal errors, with playback continuing. As we currently cannot distinguish between fatal and non-fatal device errors, we do not transition to the ERROR state, as this would cause non-fatal errors to stop playback.

When our TAL apps receive a Media Player error event, we do display an error message to the user, but immediately hide it if we receive an event which infers that it was a non-fatal error i.e. PLAYING, PAUSED, COMPLETE, or STATUS.

We do have an ambition to differentiate fatal and non-fatal device errors, so that we can attempt to recover from fatal errors (e.g. retry or change source), but we do not currently have that capability.

Full information on our media player errors can be found here: http://fmtvp.github.io/tal/overview/new-media-playback.html#errors.

Please feel free to contact us with any further queries. We would love to know how you are getting on with using TAL!

Thanks,

Tom
