### ISSUE TITLE
CSS classes not applied to image when renderMode is RENDER_MODE_IMG

### ISSUE THREAD

**Issue by ultracrepidarian** [fmtvp/tal#360]
When renderMode is RENDER_MODE_IMG, addClass has no effect before render.

var img  = new Image("myimage", "images/my_image.jpg");
img.setRenderMode(Image.RENDER_MODE_IMG);
img.addClass("spiffy");
this.appendChildWidget(img);

The resulting IMG in the DOM has no classes.

The render method in image does not add classes itself, it calls _super for RENDER_MODE_CONTAINER, which does add the classes - but this is not done for RENDER_MODE_IMG

**Comment by tsadler1988** [comment]
Hi @ultracrepidarian,

Thank you for raising this. We only ever use RENDER_MODE_CONTAINER ourselves, so do not experience this problem.

This probably isn't something we are going to fix ourselves, and if we don't receive a pull request to fix it we will most likely drop support for it in TAL v5.x.x.

I will leave this issue open so that you or another contributor can submit a fix, but I would suggest you use RENDER_MODE_CONTAINER or add classes after rendering for the time being.

Tom

**Comment by gsmithu** [comment]
Hi @tsadler1988,

We have a proposed fix for this and were wondering if you could explain the procedure for submitting the pull request.

I've tried branching, but get _403_ when I try to push the branch.

Cheers,

Gareth

**Comment by AlexChesters** [comment]
Hi @gsmithu,

Could you please fork this repo and submit a PR?

You can find instructions [here](https://help.github.com/articles/fork-a-repo/) on how to do that.

Thanks!

**Comment by gsmithu** [comment]
Thanks @AlexChesters.

Have submitted PR #363.

**Comment by subsidel** [comment]
Closed by #363
