### ISSUE TITLE
npm install throws many errors

### ISSUE THREAD

**Issue by jmalk** [fmtvp/tal#380]
Using node v4.4.7 and npm 2.15.8 on OSX 10.11.5 (El Capitan).

Ran:

```
rm -rf node_modules
npm install
```

Here is a gist of the output: https://gist.github.com/jmalk/c8c9e34c0aedb26bfd703fd789206cb7

The ELIFECYCLE error appears to be due to node-gyp's dependencies. http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm

I suggest that [the testing documentation](http://fmtvp.github.io/tal/testing.html) may need updating to include prerequisite steps before `npm install`.

Strangely, I can run `grunt test` and `grunt spec` after the failed `npm install`, so maybe the dependencies are not necessary for these commands.

**Comment by AlexChesters** [comment]
@jmalk what's your Xcode version? (`xcodebuild -version`)?

**Comment by AlexChesters** [comment]
This error also occurs with `node: 6.5.0` and `npm 3.10.3`.

**Comment by ultracrepidarian** [comment]
There are plenty more node-gyp errors waiting in the wings when trying to install TAL on Windows.  I'm getting one about a duplicate definition in the pthread C header file. It's caused by Microsoft's C/C++ build tools and there does not seem to be an easy way round it.

As node-gyp is a dependency of exec-sync, you could locally remove exec-sync from the package.json to circumvent the problem. It's only used by the jsdoc step in the gruntfile (exec-sync runs the external command on the OS, and the command itself has a very linux, i.e. non-Windows, look to it). And exec-sync is no longer maintained, since its functionality is now available in native node.js - see https://github.com/jeremyfa/node-exec-sync

Perhaps the exec-sync step is due for overhaul?
