### ISSUE TITLE
Duplicate loadURL method

### ISSUE THREAD

**Issue by ultracrepidarian** [fmtvp/tal#382]
antie/devices/net/default and antie/devices/net/xhrthiswindow both have implementations of loadURL.  They are cut and paste duplicates of each other, with the single difference being that one of them uses "this" to reference the xhr variable.  We are looking to include TTML in the list of recognised response types for this and don't really want to duplicate this code too.

It seems to me that the version of loadURL in xhrthiswindow would always work, recardless of the value of the "this" reference. And I propose to move the xhrthiswindow version into default. Can leave xhrthiswindow empty if this makes life easier for code that uses it.

Would this be acceptable to people?

**Comment by tsadler1988** [comment]
Hi @ultracrepidarian,

We agree that there is no need for there to be 2 modifiers, and would want `xhrthiswindow` to be completely removed (causing a major version increase for TAL). 

Given that this would leave us with only 1 modifier, unless we anticipate a need for divergent networking strategies we should probably refactor networking so that it is provided as standard by `antie/device/device`, rather than needing to be explicitly defined as a modifier in the device configs.

Thanks,

Tom

**Comment by tsadler1988** [comment]
Fixed by #384.
